"""
Game balance constants. Tweak here to rebalance the game.
"""

# Economy
DAILY_SALARY_PER_SKILL = 30
STARTING_BUDGET = 500
REPAIR_COST = 20
REPAIR_AMOUNT = 50

# Win/Lose
BANKRUPTCY_REP = -20
DEBT_LIMIT = -200
DEBT_DAYS_LIMIT = 2

# Time
WORK_START_HOUR = 9
WORK_END_HOUR = 21

# Events
RANDOM_EVENT_CHANCE = 0.08

# Spawning
SPAWN_BASE_RATE = 0.3
SPAWN_REP_FACTOR = 0.01
SPAWN_MULT_MIN = 0.1
SPAWN_VARIANCE_LOW = 0.8
SPAWN_VARIANCE_HIGH = 1.2

# Guests
GUEST_BUDGET_MEAN = 40.0
GUEST_BUDGET_STDDEV = 15.0
GUEST_BUDGET_MIN = 5.0
GUEST_PATIENCE_MIN_MINUTES = 5
GUEST_PATIENCE_MAX_MINUTES = 15
GUEST_BASE_EXPECTATION = 3.0
GUEST_EXPECTATION_REP_FACTOR = 0.05

# Service
QUALITY_STAFF_WEIGHT = 0.7
QUALITY_EQUIP_WEIGHT = 0.3
SERVICE_BASE_STAMINA_DRAIN = 8
SERVICE_STAMINA_PER_EXP_MULT = 2
SUCCESS_INCOME_MULT = 1.2
SUCCESS_REP_BASE = 3
FAILURE_REP_BASE = 10
GUEST_LEFT_REP_BASE = 5

# Stamina
STAMINA_RECOVERY_BASE = 5
STAMINA_RECOVERY_KITCHEN_BONUS = 0.5

# Equipment
EQUIP_DEGRADE_PER_SERVICE = 1

# UI (pygame-specific)
WINDOW_WIDTH = 960
WINDOW_HEIGHT = 640
BG_COLOR = (26, 26, 46)
FPS = 60
DEFAULT_TICK_INTERVAL = 0.5  # seconds between ticks at 1x speed

# Equipment shop tiers: (display_name, price, quality, max_durability)
EQUIPMENT_TIERS = {
    0: ("Basic", 50, 1, 80),
    1: ("Standard", 100, 3, 120),
    2: ("Premium", 180, 5, 150),
}
