"""
Game balance constants. Tweak here to rebalance the game.
"""

# Economy
DAILY_SALARY_PER_SKILL = 30
STARTING_BUDGET = 500
REPAIR_COST = 20
REPAIR_AMOUNT = 50

# Win/Lose (bankruptcy)
REP_MIN = -50
REP_MAX = 100
DAILY_EVENT_CHANCE = 0.20
EQUIP_LOW_DURABILITY = 20

# Time
WORK_START_HOUR = 9
WORK_END_HOUR = 21
TOTAL_TICKS_PER_DAY = 100

# Events (tick)
RANDOM_EVENT_CHANCE = 0.08

# Spawning
SPAWN_BASE_RATE = 0.3
SPAWN_REP_FACTOR = 0.01
SPAWN_VARIANCE_LOW = 0.8
SPAWN_VARIANCE_HIGH = 1.2

TIME_OF_DAY_MULTIPLIERS = {
    (0, 20): 0.5,
    (20, 40): 1.5,
    (40, 60): 2.0,
    (60, 80): 1.5,
    (80, 100): 0.5,
}

# Guests
GUEST_BUDGET_MEAN = 40.0
GUEST_BUDGET_STDDEV = 15.0
GUEST_BUDGET_MIN = 5.0
GUEST_PATIENCE_MIN = 3
GUEST_PATIENCE_MAX = 8
GUEST_BASE_EXPECTATION = 3.0
GUEST_EXPECTATION_REP_FACTOR = 0.05

# Service
QUALITY_STAFF_WEIGHT = 0.7
QUALITY_EQUIP_WEIGHT = 0.3
SERVICE_DURATION = 5
SUCCESS_INCOME_MULT = 1.2
SUCCESS_REP_GAIN = 3
FAILURE_COST_MULT = 0.3
FAILURE_REP_LOSS = 10
GUEST_LEFT_REP_LOSS = 2

# Stamina
REST_THRESHOLD = 0.3
REST_RECOVERY_RATE = 2

# Equipment
EQUIP_DEGRADE_PER_SERVICE = 1

# Tables
MAX_TABLES = 20
TABLE_CAPACITIES = {"small": 2, "medium": 4, "large": 6}

# UI (pygame-specific)
WINDOW_WIDTH = 960
WINDOW_HEIGHT = 640
BG_COLOR = (26, 26, 46)
FPS = 60
DEFAULT_TICK_INTERVAL = 0.5

# Equipment shop tiers: (display_name, price, quality, max_durability)
EQUIPMENT_TIERS = {
    0: ("Basic", 50, 1, 80),
    1: ("Standard", 100, 3, 120),
    2: ("Premium", 180, 5, 150),
}